### ISSUE TITLE
BodyParser limit 100kb is too small for push_bulk. Returns error 413

### ISSUE THREAD

**Issue by thomasesr** [matrix-org/matrix-appservice-discord#622]
The body parser module is being used without explicit declaration of the limit which defaults to 100kb. If Matrix tries to push_bulk messages it will throw an error on the bridge and the matrix homeserver will get a 413 response.

Console Output from the Bridge:
```
PayloadTooLargeError: request entity too large
    at readStream (/git/matrix-appservice-discord/node_modules/raw-body/index.js:155:17)
    at getRawBody (/git/matrix-appservice-discord/node_modules/raw-body/index.js:108:12)
    at read (/git/matrix-appservice-discord/node_modules/body-parser/lib/read.js:77:3)
    at jsonParser (/git/matrix-appservice-discord/node_modules/body-parser/lib/types/json.js:135:5)
    at Layer.handle [as handle_request] (/git/matrix-appservice-discord/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/git/matrix-appservice-discord/node_modules/express/lib/router/index.js:317:13)
    at /git/matrix-appservice-discord/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/git/matrix-appservice-discord/node_modules/express/lib/router/index.js:335:12)
    at next (/git/matrix-appservice-discord/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/git/matrix-appservice-discord/node_modules/express/lib/middleware/init.js:40:5)

```
Output from Homeserver.log:

```
2020-10-11 07:54:42,255 - synapse.appservice.api - 228 - WARNING - as-recoverer-discord-bridge-0 - push_bulk to http://localhost:9005/transactions/2 received 413
2020-10-11 07:54:46,279 - synapse.appservice.api - 228 - WARNING - as-recoverer-discord-bridge-0 - push_bulk to http://localhost:9005/transactions/2 received 413
```

After changing the hardcoded 100kb limit directly it went through with the transaction.

**Comment by paftree** [comment]
I have encountered this also. Where is this 100kb limit defined / overridable?

**Comment by thomasesr** [comment]
You have to change the lines on the node_modules/body-parser/lib/types/*.js files where you have:

```
  var limit = typeof opts.limit !== 'number'
    ? bytes.parse(opts.limit || '100kb')
    : opts.limit
```

I changed mine to 100mb, which is probably overkill. After the bulk synchronization is done, you can return them to the original values. But this limits should be set by the function that calls it on the matrix-discord-appservice code. This 100kb limit is hard coded as a default value on the body-parser node module but it is overwritable and should be defined by the application that calls that module.

**Comment by karolyi** [comment]
this is great help, thank you. it seems that according to the code there is `opts.limit`, it would need to be passed to the code and the manual changes wouldn't be necessary.

**Comment by vranki** [comment]
This commit updates the sdk version and removes the 100kb limit: https://github.com/Half-Shot/matrix-appservice-discord/commit/2f37665ae8c5ee1b8345a0165e100bf9972e2c64

I believe this issue is fixed in develop now.

**Comment by jaller94** [comment]
Apparently fixed but needs a stable release.
